version: '3.9'

services:
  web:
    build:
      context: .
      target: php-web
      #image: deforay/vlsm-web:latest
    ports:
      - "${APACHE_PORT:-80}:80"
    volumes:
      #- app_code:/var/www/html
      - .:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - DOMAIN=${DOMAIN:-vlsm}
      - APACHE_PORT=${APACHE_PORT:-80}
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-strict-mode=OFF --sql-mode=""
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-my_database}
      #- MYSQL_USER=${MYSQL_USER:-my_user}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD:-my_password}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  #app_code: {}
  db_data: {}
