version: '3.9'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/php-apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php-apache/conf.d/php.ini:/etc/php/7.4/apache2/conf.d/custom-php.ini
    restart: always      
  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vlsm
    restart: always
