-- Migration file for version 5.5.23
--
-- Stores the activity the Interface Tool records about its instruments:
-- connection attempts, connection failures and application starts.
--
-- Events reach this table two ways, the importer reading the tool's local
-- database and the tool posting them over the API, so `event_uid` is unique to
-- make a repeated delivery a no-op rather than a duplicate row. `lab_id` is
-- always derived from the caller and never taken from the payload.

CREATE TABLE IF NOT EXISTS `instrument_activity_log` (
  `activity_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_uid` CHAR(36) NOT NULL COMMENT 'Identifier generated by the Interface Tool',
  `lab_id` INT NOT NULL COMMENT 'Derived from the credential or system config, never the payload',
  `installation_id` CHAR(36) NULL DEFAULT NULL COMMENT 'Set when the event arrived over the API',
  `received_via` VARCHAR(16) NOT NULL DEFAULT 'api' COMMENT 'api or importer',
  `event_type` VARCHAR(64) NOT NULL,
  `event_category` VARCHAR(32) NOT NULL,
  `occurred_at` DATETIME NOT NULL,
  `instrument_id` VARCHAR(128) NULL DEFAULT NULL,
  `machine_type` VARCHAR(128) NULL DEFAULT NULL,
  `protocol` VARCHAR(32) NULL DEFAULT NULL,
  `connection_mode` VARCHAR(32) NULL DEFAULT NULL,
  `test_type` VARCHAR(128) NULL DEFAULT NULL,
  `outcome` VARCHAR(32) NOT NULL DEFAULT 'success',
  `failure_code` VARCHAR(64) NULL DEFAULT NULL,
  `event_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `app_version` VARCHAR(32) NULL DEFAULT NULL,
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`activity_id`),
  UNIQUE KEY `uniq_instrument_activity_event_uid` (`event_uid`),
  KEY `idx_instrument_activity_lab_time` (`lab_id`, `occurred_at`),
  KEY `idx_instrument_activity_type_time` (`event_type`, `occurred_at`),
  KEY `idx_instrument_activity_instrument_time` (`instrument_id`, `occurred_at`),
  KEY `idx_instrument_activity_outcome_time` (`outcome`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

UPDATE `system_config` SET `value` = '5.5.23' WHERE `system_config`.`name` = 'sc_version';

-- END OF VERSION --
