-- Migration file for version 5.5.27
--
-- Stores the daily test volume each Interface Tool instrument reports: how many
-- tests it ran on a given day, how many succeeded and how many failed.
--
-- This is deliberately not kept in instrument_activity_log. That table is an
-- append-only record of things that happened; a daily summary is a running total
-- that the tool revises all day as more tests complete. `revision` is what tells
-- a later summary from an earlier one, so an out-of-order delivery cannot undo a
-- newer count.
--
-- Counts are absolute, never increments: a summary replaces the day's figures
-- rather than adding to them, which is what makes a repeated delivery harmless.
--
-- `aggregate_uid` is generated by the Interface Tool. It is unique per lab rather
-- than globally, so two labs cannot collide and neither can overwrite the other.
-- `lab_id` is always derived from the caller and never taken from the payload.

CREATE TABLE IF NOT EXISTS `instrument_usage_statistics_daily` (
  `usage_statistic_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aggregate_uid` CHAR(36) NOT NULL COMMENT 'Identifier generated by the Interface Tool',
  `lab_id` INT NOT NULL COMMENT 'Derived from the credential or system config, never the payload',
  `installation_id` CHAR(36) NULL DEFAULT NULL COMMENT 'Set when the summary arrived over the API',
  `received_via` VARCHAR(16) NOT NULL DEFAULT 'api' COMMENT 'api or importer',
  `activity_date` DATE NOT NULL COMMENT 'The day these counts describe',
  `instrument_id` VARCHAR(128) NULL DEFAULT NULL,
  `machine_type` VARCHAR(128) NULL DEFAULT NULL,
  `test_type` VARCHAR(128) NULL DEFAULT NULL,
  `total_tests` INT UNSIGNED NOT NULL DEFAULT 0,
  `successful_tests` INT UNSIGNED NOT NULL DEFAULT 0,
  `failed_tests` INT UNSIGNED NOT NULL DEFAULT 0,
  `first_test_at` DATETIME NULL DEFAULT NULL,
  `last_test_at` DATETIME NULL DEFAULT NULL,
  `revision` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Increases as the tool revises the day',
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usage_statistic_id`),
  UNIQUE KEY `uniq_instrument_usage_lab_aggregate` (`lab_id`, `aggregate_uid`),
  KEY `idx_instrument_usage_lab_date` (`lab_id`, `activity_date`),
  KEY `idx_instrument_usage_instrument_date` (`instrument_id`, `activity_date`),
  KEY `idx_instrument_usage_test_date` (`test_type`, `activity_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

UPDATE `system_config` SET `value` = '5.5.27' WHERE `system_config`.`name` = 'sc_version';

-- END OF VERSION --
