<?php

// DO NOT MODIFY THIS FILE
// Version is defined in composer.json
// This file is automatically generated by bin/build/generate-version.php
defined('VERSION')
    || define('VERSION', '5.5.23');
