<?php

namespace App\Helpers;

use Override;
use App\Utilities\MiscUtility;
use App\Utilities\DateUtility;
use TCPDF;

class ManifestPdfHelper extends TCPDF
{
    public ?string $logo = "";
    public string $text = "";
    public ?string $labname = "";
    public ?string $manifestType;

    public function setHeading(?string $logo, string $text, ?string $labname): void
    {
        $this->logo = $logo;
        $this->text = $text;
        $this->labname = $labname;
    }

    public function __construct($manifestType = "", $orientation = 'P', $unit = 'mm', $format = 'A4', $unicode = true, $encoding = 'UTF-8', $diskcache = false, $pdfa = false)
    {
        parent::__construct($orientation, $unit, $format, $unicode, $encoding, $diskcache, $pdfa);
        $this->manifestType = $manifestType ?: _translate("Sample Referral Manifest");
    }

    //Page header
    #[Override]
    public function Header(): void
    {
        if (trim((string) $this->logo) != "" && MiscUtility::isImageValid(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo)) {
            $imageFilePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo;
            $this->Image($imageFilePath, 15, 10, 15, '', '', '', 'T');
        }
        $this->SetFont('helvetica', '', 7);
        $this->writeHTMLCell(30, 0, 10, 26, $this->text, 0, 0, 0, true, 'A');
        $this->SetFont('helvetica', '', 13);
        $this->writeHTMLCell(0, 0, 0, 10, $this->manifestType, 0, 0, 0, true, 'C');
        $this->SetFont('helvetica', '', 10);
        $this->writeHTMLCell(0, 0, 0, 20, $this->labname, 0, 0, 0, true, 'C');

        if (trim((string) $this->logo) != "" && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo)) {
            $imageFilePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo;
            $this->Image($imageFilePath, 262, 10, 15, '', '', '', 'T');
        }
        $this->SetFont('helvetica', '', 7);
        $this->writeHTMLCell(30, 0, 255, 26, $this->text, 0, 0, 0, true, 'A');
        $html = '<hr/>';
        $this->writeHTMLCell(0, 0, 10, 32, $html, 0, 0, 0, true, 'J');
    }

    // Page footer
    #[Override]
    public function Footer(): void
    {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', '', 8);
        // Page number
        $this->Cell(0, 10,  'Specimen Manifest Generated On : ' . date('d/m/Y H:i:s') . ' | Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, false, 'C', 0);
    }

    /**
     * Initialize PDF with standard settings
     */
    public function initializeManifest(string $logo, string $header, string $labname): void
    {
        $this->setHeading($logo, $header, $labname);
        $this->SetCreator('VLSM');
        $this->SetAuthor('VLSM');
        $this->SetTitle('Specimen Referral Manifest');
        $this->SetSubject('Specimen Referral Manifest');
        $this->SetKeywords('Specimen Referral Manifest');
        $this->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
        $this->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
        $this->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);
        $this->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
        $this->SetMargins(PDF_MARGIN_LEFT, 36, PDF_MARGIN_RIGHT);
        $this->SetHeaderMargin(PDF_MARGIN_HEADER);
        $this->SetFooterMargin(PDF_MARGIN_FOOTER);
        $this->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);
        $this->setImageScale(PDF_IMAGE_SCALE_RATIO);
        $this->SetFont('helvetica', '', 10);
        $this->setPageOrientation('L');
        $this->AddPage();
    }

    /**
     * Render manifest code with barcode
     */
    public function renderManifestCodeSection(string $code, string $barcodeImg): string
    {
        return '<p></p><span style="font-size:1.7em;"> ' . htmlspecialchars($code) .
            '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img style="width:200px;height:30px;" src="' . $barcodeImg . '">' .
            '</span><br>';
    }

    /**
     * Render signature section
     */
    public function renderSignatureSection(string $generatedBy, string $labName): string
    {
        $html = '<br><br><br><br><table cellspacing="0" style="width:100%;">';
        $html .= '<tr>';
        $html .= '<td align="left" style="vertical-align:middle;font-size:11px;width:33.33%;"><strong>' . _translate('Generated By') . ' : </strong><br>' . htmlspecialchars($generatedBy) . '</td>';
        $html .= '<td align="left" style="vertical-align:middle;font-size:11px;width:33.33%;"><strong>' . _translate('Verified By') . ' :  </strong></td>';
        $html .= '<td align="left" style="vertical-align:middle;font-size:11px;width:33.33%;"><strong>' . _translate('Received By') . ' : </strong><br>(at ' . htmlspecialchars($labName) . ')</td>';
        $html .= '</tr>';
        $html .= '</table><br><br>';
        return $html;
    }

    /**
     * Render change history section
     */
    public function renderChangeHistory(array $reasonHistory, callable $getUserName): string
    {
        if (empty($reasonHistory)) {
            return '';
        }

        $html = _translate('Manifest Change History');
        $html .= '<br><br><table nobr="true" style="width:100%;" border="1" cellpadding="2"><tr nobr="true">';
        $html .= '<th>' . _translate('Reason for Change') . '</th>';
        $html .= '<th>' . _translate('Changed By') . '</th>';
        $html .= '<th>' . _translate('Changed On') . '</th>';
        $html .= '</tr>';

        foreach ($reasonHistory as $change) {
            $userName = $getUserName($change->changedBy ?? '');
            $html .= '<tr nobr="true">';
            $html .= '<td align="left" style="vertical-align:middle;font-size:11px;width:33.33%;">' . htmlspecialchars($change->reason ?? '') . '</td>';
            $html .= '<td align="left" style="vertical-align:middle;font-size:11px;width:33.33%;">' . htmlspecialchars($userName) . '</td>';
            $html .= '<td align="left" style="vertical-align:middle;font-size:11px;width:33.33%;">' . DateUtility::humanReadableDateFormat($change->date ?? '') . '</td>';
            $html .= '</tr>';
        }
        $html .= '</table>';
        return $html;
    }

    /**
     * Render Sierra Leone facility releaser information
     */
    public function renderSierraLeoneReleaserInfo(array $data): string
    {
        $html = '<strong>FACILITY RELEASER INFORMATION</strong>';
        $html .= '<br><table nobr="true" style="width:100%;" border="0" cellpadding="2">';
        $html .= '<tr>
            <td align="left"> Releaser Name :  ' . htmlspecialchars($data['releaser_name'] ?? '') . '</td>
            <td align="left"> Date :  ' . htmlspecialchars($data['created_date'] ?? '') . '</td>
        </tr>
        <tr>
            <td align="left"> Phone No. :  ' . htmlspecialchars($data['phone'] ?? '') . '</td>
            <td align="left"> Email :  ' . htmlspecialchars($data['email'] ?? '') . '</td>
        </tr>
        <tr>
            <td align="left"> Facility Name :  ' . htmlspecialchars($data['clinic_name'] ?? '') . '</td>
            <td align="left"> District :  ' . htmlspecialchars($data['facility_district'] ?? '') . '</td>
        </tr>';
        $html .= '</table>';
        return $html;
    }

    /**
     * Render Sierra Leone specimen packaging section
     */
    public function renderSierraLeonePackaging(int $numberOfSamples): string
    {
        $html = '<p></p><strong>SPECIMEN PACKAGING</strong>';
        $html .= '<br><table nobr="true" style="width:100%;" border="0" cellpadding="2">';
        $html .= '<tr>
            <td align="left"> Number of specimen included :  ' . $numberOfSamples . '</td>
            <td align="left"> Forms completed and included :  Yes / No</td>
        </tr>
        <tr>
            <td align="left"> Packaged By :  ..................</td>
            <td align="left"> Date :  ...................</td>
        </tr>';
        $html .= '</table>';
        return $html;
    }

    /**
     * Render chain of custody section
     */
    public function renderChainOfCustody(string $title, string $fromLabel, string $toLabel): string
    {
        $html = '<p></p><strong>' . htmlspecialchars($title) . '</strong>';
        $html .= '<br><table border="1">
        <tr>
            <td colspan="2">' . htmlspecialchars($fromLabel) . '</td>
            <td colspan="2">' . htmlspecialchars($toLabel) . '</td>
        </tr>
        <tr>
            <td align="left"> Name : <br><br> Sign : <br><br> Phone No. :</td>
            <td align="left"> Date : <br><p></p><br> Time :</td>
            <td align="left"> Name : <br><br> Sign : <br><br> Phone No. :</td>
            <td align="left"> Date : <br><p></p><br> Time :</td>
        </tr>
        </table>';
        return $html;
    }

    /**
     * Render full Sierra Leone/Rwanda sections
     */
    public function renderCountrySpecificSections(array $data, int $numberOfSamples): void
    {
        $this->WriteHTML($this->renderSierraLeoneReleaserInfo($data));
        $this->writeHTMLCell('', '', 11, $this->getY(), '', 0, 1, 0, true, 'C');

        $this->writeHTMLCell('', '', 11, $this->getY(), $this->renderSierraLeonePackaging($numberOfSamples), 0, 1, 0, true, 'C');

        $this->WriteHTML('<p></p><strong>CHAIN OF CUSTODY : </strong>(persons relinquishing and receiving specimen fill their respective sections)');
        $this->WriteHTML('<p></p><strong>To be completed at facility in the presence of specimen courier</strong>');
        $this->writeHTMLCell('', '', 11, $this->getY(), $this->renderChainOfCustody('', 'Relinquished By (Laboratory)', 'Received By (Courier)'), 0, 1, 0, true, 'C');

        $this->WriteHTML('<p></p><strong>To be completed at testing laboratory by specimen reception personnel</strong>');
        $this->writeHTMLCell('', '', 11, $this->getY(), $this->renderChainOfCustody('', 'Relinquished By (Courier)', 'Received By (Laboratory)'), 0, 1, 0, true, 'C');
    }

    /**
     * Output manifest to file and return filename
     */
    public function outputManifest(string $manifestCode): string
    {
        $filename = trim($manifestCode) . '-' . date('Ymd') . '-' . MiscUtility::generateRandomString(6) . '-Manifest.pdf';
        $manifestsPath = MiscUtility::buildSafePath(TEMP_PATH, ["sample-manifests"]);
        $filename = MiscUtility::cleanFileName($filename);
        $this->Output($manifestsPath . DIRECTORY_SEPARATOR . $filename, "F");
        return $filename;
    }
}
